name: apn_widgets
description: A carefully curated collection of widget made by and used within Appnormal projects
version: 1.1.8
homepage: https://appnormal.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  apn_http:
  apn_analytics:

  cupertino_icons: ^1.0.0
  keyboard_visibility: ^0.5.6
  app_settings: ^4.0.4
  flare_flutter: ^2.0.6
  image_picker: ^0.6.7+12
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/animations/
    - lib/assets/
    - lib/assets/2.0x/
    - lib/assets/3.0x/