name: apn_widgets
description: A carefully curated collection of widget made by and used within Appnormal projects
version: 2.0.0
homepage: https://appnormal.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  app_settings: ^4.1.0
  flare_flutter: ^3.0.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/animations/
    - lib/assets/
    - lib/assets/2.0x/
    - lib/assets/3.0x/